### ISSUE TITLE
Create a discord message template

### ISSUE THREAD

**Issue by KushGabani** [KushGabani/radiokey#1]
It's very painful to write the `message.channel.send({ })` for every message to be sent by the discord bot. The task is to simply create a new file named the `src/templates/message.js`.

In this file, you need to export a function that can then be used in any other file as a message template. The function should be named `sendMessage()`. Below is the definition of the function to be followed:
```javascript
const sendMessage = (message, title="", description="", fields=[]) => {
}
````

Before contributing, make sure you follow the guidelines in [Contributions.md](https://github.com/KushGabani/radiokey/blob/main/Contributions.md)
Thanks! **Happy Contributions** ✨

**Comment by NakulTikiwala** [comment]
Hi kush. This is my first time contributing to an open source project. It would be great if you could assign me to this task.

**Comment by KushGabani** [comment]
Yes, sure! Make sure you refer to the contribution guidelines in the root of the repository. Thanks!

**Happy Contributions** ✨

**Comment by NakulTikiwala** [comment]
Yes, Thank you so much. This is my first js project. I'm excited.

**Comment by NakulTikiwala** [comment]
Hi again, this may seem silly but I've pushed my changes to the forked repository. How do I create the so called pull request?

**Comment by NakulTikiwala** [comment]
Nevermind, I found an blogpost online. Thanks
