### ISSUE TITLE
Create a sample.env file to contain the template of the .env file

### ISSUE THREAD

**Issue by KushGabani** [KushGabani/radiokey#3]
Create a `sample.env` file at the root of the directory. As an `.env` file is not advised to display publicly because it contains sensitive information. You need to create a `sample.env` file with the following content:
```javascript
BOT_TOKEN=YOUR_BOT_TOKEN_HERE
```

Once the file has been created, you also need to make changes in the read me file for the developers and contributors. After Step 4, create a new step containing the following steps:

---

Create .env to contain the bot token. A sample.env file has already been provided.
   ```shell
   copy sample.env .env
   ```
   Once the .env file is created, replace it with your bot token in .env

---

Before contributing, make sure you follow the guidelines in [Contributions.md](https://github.com/KushGabani/radiokey/blob/main/Contributions.md)
Thanks! **Happy Contributions** ✨

**Comment by thehimanshukashyap** [comment]
Hello!!! I'm interested in this project. Can I contribute to this project or try fixing this issue??

**Comment by KushGabani** [comment]
Definitely. I'll assign you to the issue. Make sure you refer to the Contribution guidelines. Thanks!
