### ISSUE TITLE
Add automated code scanning workflow

### ISSUE THREAD

**Issue by KushGabani** [KushGabani/radiokey#5]
Setup a CodeQL Analysis workflow to automatically detect common vulnerabilities and coding errors for JavaScript when a pull request is merged or a commit is made to the main branch.

Before contributing, make sure you follow the guidelines in [Contributions.md](https://github.com/KushGabani/radiokey/blob/main/Contributions.md)
Thanks! **Happy Contributions** ✨

**Comment by ManavD522** [comment]
This is my first open-source contribution. Can you assign me to it?

**Comment by KushGabani** [comment]
Sure. Make sure you first read the contributing guidelines and the readme for this repository. Thanks for your contribution!
