### ISSUE TITLE
Create a file that handles basic checks

### ISSUE THREAD

**Issue by KushGabani** [KushGabani/radiokey#6]
Your task here is to Prevent code duplication.
Until now, every action i.e. command for the music player needs to ensure basic checks like

- If the bot has connected to the voice channel
- where the voice channel in which the bot is connected is the same as the voice channel of the member
- If the queue is already empty or not
etc...

Create a new file in `src/templates/validations` where these methods will reside and are called as and when needed. This will make the code more manageable and easy to refer.

Before contributing, make sure you follow the guidelines in [Contributions.md](https://github.com/KushGabani/radiokey/blob/main/Contributions.md)
Thanks! **Happy Contributions** ✨

**Comment by SmitMewada** [comment]
I'll like to continue with this issue. Please assign me this issue.
