### ISSUE TITLE
Fix typos, debug with correct syntax and bind actions to events

### ISSUE THREAD

**Issue by KushGabani** [KushGabani/radiokey#9]
Due to a fault merge from a branch, the `src/actions/*.js` files do not have the correct prefix stated in its utilization property.

The `src/core-commands/debug.js` does not have proper syntax for its `message.channel.send()` and the `src/core-commands/ping.js` does not have a proper category of "core" assigned to it.

Along with this, `src/index.js` files must also register the action and bind with its corresponding event.

Your task is to fix these typos and syntax errors if you're a beginner.
A relatively more experienced developer can register each action to the discord client.

Make sure you read the contributions.md before you start your work.
**Happy Contributions** ✨

**Comment by kesarbhimani** [comment]
Can you please assign me to it? I'd like to resolve this issue.

**Comment by KushGabani** [comment]
Yes, @kesarbhimani. Make sure you read the contribution guidelines in the repository

**Comment by kesarbhimani** [comment]
Can I refactor some other part of the data like console logs?

**Comment by KushGabani** [comment]
Yes but make sure you don't edit or accidentally delete important parts of the code. Try restricting yourself to only the files mentioned in the issue.
